import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal:23
  },
  header: {
    paddingTop: 24,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 32,
    letterSpacing: -0.48,
  },
  content: {
    flex: 1,
  },
  timelineContainer: {
    paddingVertical: 10,
  },
  stepWrapper: {
    position: 'relative',
  },
  stepContainer: {
    marginBottom: 8,
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
  },
  stepIconContainer: {
    marginRight: 10,
    zIndex: 1,
  },
  completedIcon: {
    width: 32,
    height: 32,
    borderRadius: 100,
    backgroundColor: '#D1FADF',
    alignItems: 'center',
    justifyContent: 'center',
    // paddingTop: 8,
    // paddingRight: 17,
    // paddingBottom: 8,
    // paddingLeft: 17,
  },
  checkmark: {
    color: '#054F31',
    fontSize: 14,
    fontWeight: '600',
  },
  activeIcon: {
    width: 32,
    height: 32,
    borderRadius: 100,
    backgroundColor: '#0BA5EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeIconText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  pendingIcon: {
    width: 32,
    height: 32,
    borderRadius: 100,
    backgroundColor: '#E9EAEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingIconText: {
    color: '#000000',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  stepInfo: {
    flex: 1,
    paddingTop: 2,
  },
  stepTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: 8,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 24,
    flex: 1,
  },
  timeAgoPill: {
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  timeAgoText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
  },
  donePill: {
    backgroundColor: '#D1FADF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  doneText: {
    fontSize: 12,
    color: '#054F31',
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
  },
  activePill: {
    backgroundColor: '#DBEAFE',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  activePillText: {
    fontSize: 12,
    color: '#3B82F6',
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  stepDescription: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    fontWeight:'400',
    paddingBottom:6
  },
  stepSubText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    marginTop: 4,
  },
  estimatedTimeText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    marginTop: 4,
    fontStyle: 'italic',
  },
  actionButton: {
    backgroundColor: '#983614',
    height: 44,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: '#983614',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    gap: 8,
    alignSelf: 'flex-start',
  },
  actionButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  actionButtonIcon: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  expandButton: {
    padding: 4,
    marginTop: 2,
  },
  expandIcon: {
    width: 16,
    height: 16,
    transform: [{ rotate: '90deg' }],
  },
  expandIconRotated: {
    transform: [{ rotate: '270deg' }],
  },
  timelineLine: {
    position: 'absolute',
    left: 15,
    top: 32,
    width: 2,
    bottom: -12,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 0,
  },
  onboardedMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal:10
  },
  boomIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  onboardedMessageText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 24,
    flex: 1,
  },
  footer: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkboxContainer: {
    marginRight: 12,
    marginTop: 2,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxCheckmark: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  termsText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#6B7280',
    fontFamily: 'Saans TRIAL',
    lineHeight: 20,
    flex: 1,
  },
  termsLink: {
    fontSize: 14,
    fontWeight: '500',
    color: '#983614',
    fontFamily: 'Saans TRIAL',
    lineHeight: 20,
  },
  privacyLink: {
    fontSize: 14,
    fontWeight: '500',
    color: '#983614',
    fontFamily: 'Saans TRIAL',
    lineHeight: 20,
  },
  captureButton: {
    backgroundColor: '#0BA5EC',
    height: 52,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  captureButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Saans TRIAL',
  },
  submitButton: {
    marginTop: 12,
    borderRadius: 100,
    overflow: 'hidden',
    width: '100%',
  },
  submitButtonGradient: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Saans TRIAL',
  },
});
