import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 12,
    paddingBottom: 140,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButton: {
    borderRadius: 1000,
    backgroundColor: '#FEEDD6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  helpButtonText: {
    fontSize: 16,
    color: '#983614',
    fontWeight: '600',
  },
  content: {
    gap: 24,
    marginBottom: 16,
  },
  dropdownContainer: {
    position: 'relative',
    zIndex: 1000,
  },
  inputContainer: {
    gap: 12,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
  },
  dropdownButtonFocused: {
    borderWidth: 1.5,
    borderColor: '#414651',
  },
  dropdownButton: {
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownText: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  placeholderText: {
    color: '#9CA3AF',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 8,
  },
  dropdownList: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    overflow: 'hidden',
    maxHeight: 320,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 32,
    fontFamily: 'Saans TRIAL',
    marginBottom: 8,
  },
  bottomContainer: {
    paddingBottom: 34,
    paddingTop: 20,
    paddingHorizontal: 23,
    gap: 14,
    backgroundColor: '#FFFFFF',
    zIndex: 100,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  verifyButtonTouchable: {
    borderRadius: 100,
  },
  verifyButton: {
    borderRadius: 100,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    opacity: 1,
    minHeight: 52,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  verifyButtonDisabled: {
    opacity: 0.5,
  },
  verifyButtonTextDisabled: {
    color: '#FFFFFF',
  },
  bottomSheetContent: {
    paddingVertical: 20,
    gap: 24,
  },
  successTitle: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 24,
    lineHeight: 32,
    color: '#111827',
    textAlign: 'center',
  },
  successSubtitle: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    color: '#111827',
    textAlign: 'center',
    marginBottom: 16,
  },
  whatHappensNext: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 28,
    color: '#B7410E',
    textAlign: 'center',
    marginBottom: 18,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF7ED',
    borderRadius: 12,
    padding: 12,
    gap: 12,
  },
  stepNumber: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  stepNumberText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
    color: '#B7410E',
  },
  stepContent: {
    flex: 1,
    gap: 4,
  },
  stepTitle: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
    color: '#111827',
  },
  stepDescription: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
    color: '#6B7280',
  },
  confirmButton: {
    marginTop: 20,
    borderRadius: 100,
    overflow: 'hidden',
  },
  confirmButtonGradient: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Saans TRIAL',
  },
  iconContainer: {
    alignItems: 'center',
  },
  titleContainer: {
    gap: 8,
  },
  stepsContainer: {
    backgroundColor: '#FFF7ED',
    borderRadius: 12,
    gap: 12,
    padding: 12,
  },
});
