import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  gradientContainer: {
    width: '100%',
    overflow: 'hidden',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  gradientBackground: {
    flex: 1,
    width: '100%',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  countdownText: {
    fontSize: 120,
    fontWeight: '700',
    fontFamily: 'Saans TRIAL',
    color: '#FFFFFF',
    letterSpacing: -2,
  },
  instructionText: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#FDD8AB',
  },
  shootContentWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shootContent: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  shootDurationLabel: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#FDD8AB',
    letterSpacing: 0.5,
  },
  shootDurationText: {
    fontSize: 72,
    fontWeight: '700',
    fontFamily: 'Saans TRIAL',
    color: '#FFFFFF',
    letterSpacing: -1,
  },
  shootDurationTarget: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 8,
  },
  buttonContainer: {
    paddingHorizontal: 24,
    paddingBottom: 40,
    width: '100%',
  },
  endShootButton: {
    backgroundColor: '#FFFFFF1F',
    borderRadius: 10000,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endShootButtonText: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: 'white',
  },
  eventTitleContainer: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 12,
  },
  eventTitle: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '700',
    fontSize: 30,
    lineHeight: 38,
    color: '#252B37',
  },
  requirementSection: {
    paddingHorizontal: 18,
    paddingTop: 24,
  },
  requirementTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
    marginBottom: 16,
  },
  requirementCard: {
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  requirementRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  requirementLabel: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  requirementValue: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  instantDelivery: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  addonsWrapper: {
    marginTop: 20,
  },
  addonsTitle: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
    marginBottom: 12,
  },
  addonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  addonPill: {
    backgroundColor: '#E0E0E0',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addonText: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  descriptionSection: {
    paddingHorizontal: 18,
    paddingTop: 24,
  },
  descriptionTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
    marginBottom: 16,
  },
  descriptionCard: {
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  descriptionText: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
    lineHeight: 24,
  },
  audioSection: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 24,
  },
  audioHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  audioTitle: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  suggestButton: {
    backgroundColor: '#FF6E9C',
    borderRadius: 10000,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  suggestButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    color: 'white',
  },
  songsList: {
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  songCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  songThumbnail: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
  },
  songInfo: {
    flex: 1,
  },
  songTitle: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
    color: '#181D27',
  },
  songArtist: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Saans TRIAL',
    color: 'rgba(24, 29, 39, 0.7)',
  },
});

