import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 12,
    paddingBottom: 140,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButton: {
    borderRadius: 1000,
    backgroundColor: '#FEEDD6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  helpButtonText: {
    fontSize: 16,
    color: '#983614',
    fontWeight: '600',
  },
  content: {
    gap: 24,
    marginBottom: 16,
  },
  scrollView: {
    flex: 1,
  },
  inputsContainer: {
    gap: 16,
  },
  inputContainer: {
    gap: 12,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
  },
  textInput: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
  },
  textInputFocused: {
    borderWidth: 1.5,
    borderColor: '#414651',
  },
  phoneInputContainer: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
    gap: 6,
  },
  phoneInputContainerFocused: {
    borderWidth: 1.5,
    borderColor: '#414651',
  },
  phonePrefix: {
    backgroundColor: '#F0F4F8',
    borderRadius: 5,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  phonePrefixText: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
  },
  phoneTextInput: {
    flex: 1,
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    paddingVertical: 0,
  },
  dropdownButton: {
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownText: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  placeholderText: {
    color: '#9CA3AF',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 8,
  },
  dropdownList: {
    position: 'absolute',
    top: 54,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    maxHeight: 200,
    zIndex: 1000,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 32,
    fontFamily: 'Saans TRIAL',
    marginBottom: 8,
  },
   bottomContainer: {
    paddingBottom: Platform.OS === 'ios' ? 25 : 34,
    paddingHorizontal: 23,
    gap: 32,
    backgroundColor: 'white',
    borderTopColor: '#F3F4F6',
  },
  verifyButtonTouchable: {
    borderRadius: 100,
  },
  verifyButton: {
    borderRadius: 120,
    height: 48,
    // paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    opacity: 1,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  verifyButtonDisabled: {
    opacity: 0.5,
  },
  verifyButtonTextDisabled: {
    color: '#FFFFFF',
  },
  helpText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
    fontFamily: 'Saans TRIAL',
  },
  facingIssueText: {
    color: '#414651',
  },
  changeNumberText: {
    color: '#B7410E',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmark: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '600',
  },
  checkboxText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  referralContainer: {
    backgroundColor: '#FFF7ED',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FED7AA',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  referralHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  giftIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  referralText: {
    flex: 1,
    gap: 4,
  },
  gift: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  giftText: {
    gap: 1,
  },
  referralCodeText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: '#983614',
  },
  bonusText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    color: '#717680',
  },
  referralCodeInput: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  referralCodeTextInput: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#111827',
    fontFamily: 'Saans TRIAL',
  },
  referralCodeTextInputValid: {
    borderColor: '#039855',
  },
  tickMark: {
    position: 'absolute',
    right: 12,
    color: '#039855',
    fontSize: 16,
    fontWeight: '600',
  },
});
