import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 12,
    paddingBottom: 130,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButton: {
    borderRadius: 1000,
    backgroundColor: '#FEEDD6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  helpButtonText: {
    fontSize: 16,
    color: '#983614',
    fontWeight: '600',
  },
  content: {
    marginTop: 8,
    marginBottom: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#111827',
    lineHeight: 32,
    fontFamily: 'Saans TRIAL',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#717680',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    textAlignVertical: 'center',
  },
  otpSection: {
    marginTop: 8,
    marginBottom: 24,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
  },
  otpInput: {
    flex: 1,
    height: 58,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    fontSize: 24,
    color: '#111827',
    fontWeight: '600',
    textAlign: 'center',
  },
  resendContainer: {
    paddingVertical: 12,
  },
  resendText: {
    fontSize: 14,
    color: '#B7410E',
    fontWeight: '500',
    fontFamily: 'Inter',
  },
  bottomContainer: {
    paddingBottom: 34,
    paddingTop: 20,
    paddingHorizontal: 23,
    gap: 14,
    backgroundColor: '#FFFFFF',
    zIndex: 100,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  verifyButtonTouchable: {
    borderRadius: 100,
  },
  verifyButton: {
    borderRadius: 100,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    opacity: 1,
    minHeight: 52,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  verifyButtonDisabled: {
    opacity: 0.5,
  },
  helpText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'center',
    fontFamily: 'Saans TRIAL',
  },
  facingIssueText: {
    color: '#414651',
  },
  changeNumberText: {
    color: '#B7410E',
  },
});
