import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal:23
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 23,
    paddingTop: 12,
    paddingBottom: 140,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 32,
  },
  timelineContainer: {
    paddingVertical: 10,
  },
  stepWrapper: {
    position: 'relative',
  },
  stepContainer: {
    marginBottom: 8,
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
  },
  stepIconContainer: {
    marginRight: 10,
    zIndex: 1,
  },
  completedIcon: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: '#D1FADF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmark: {
    color: '#054F31',
    fontSize: 16,
    fontWeight: '600',
  },
  activeIcon: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: '#0BA5EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeIconText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  pendingIcon: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: '#E9EAEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingIconText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  stepInfo: {
    flex: 1,
    paddingTop: 2,
  },
  stepTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    gap: 8,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 24,
    flex: 1,
  },
  timeAgoPill: {
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  timeAgoText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
  },
  donePill: {
    backgroundColor: '#D1FADF',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  doneText: {
    fontSize: 12,
    color: '#054F31',
    fontWeight: '500',
    fontFamily: 'Saans TRIAL',
  },
  activePill: {
    backgroundColor: '#DBEAFE',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  activePillText: {
    fontSize: 12,
    color: '#3B82F6',
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  stepDescription: {
    fontSize: 16,
    color: '#6B7280',
    lineHeight: 24,
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    paddingBottom: 6,
  },
  stepSubText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    marginTop: 4,
  },
  estimatedTimeText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: 'Saans TRIAL',
    marginTop: 4,
    fontStyle: 'italic',
  },
  actionButton: {
    backgroundColor: '#983614',
    minHeight: 44,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#983614',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 8,
    alignSelf: 'flex-start',
  },
  actionButtonText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
  },
  actionButtonIcon: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  expandButton: {
    padding: 8,
    marginTop: 2,
  },
  expandIcon: {
    width: 20,
    height: 20,
    transform: [{ rotate: '90deg' }],
  },
  expandIconRotated: {
    transform: [{ rotate: '270deg' }],
  },
  timelineLine: {
    position: 'absolute',
    left: 17,
    top: 48,
    width: 2,
    bottom: -12,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    zIndex: 0,
  },
  onboardedMessageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FEDDB3',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 12,
  },
  boomIcon: {
    marginTop: 2,
  },
  onboardedMessageText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#111827',
    fontFamily: 'Saans TRIAL',
    lineHeight: 24,
    flex: 1,
  },
  bottomContainer: {
    paddingBottom: 34,
    paddingTop: 20,
    paddingHorizontal: 23,
    gap: 14,
    backgroundColor: '#FFFFFF',
    zIndex: 100,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  checkboxContainer: {
    marginTop: 2,
    width: 20,
    height: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#983614',
    borderColor: '#983614',
  },
  checkboxCheckmark: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  termsText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#6B7280',
    fontFamily: 'Saans TRIAL',
    lineHeight: 18,
    flex: 1,
  },
  termsLink: {
    fontSize: 12,
    fontWeight: '500',
    color: '#983614',
    fontFamily: 'Saans TRIAL',
  },
  privacyLink: {
    fontSize: 12,
    fontWeight: '500',
    color: '#983614',
    fontFamily: 'Saans TRIAL',
  },
  submitButtonTouchable: {
    borderRadius: 100,
    overflow: 'hidden',
  },
  submitButton: {
    height: 52,
    // alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonGradient:{
    borderRadius: 120,
    height: 56,
    // paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    opacity: 1,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'Saans TRIAL',
  },
  submitButtonTextDisabled: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    fontFamily: 'Saans TRIAL',
  },

  footer:{
    gap:12


  }
});