import { StyleSheet, Dimensions } from 'react-native';
import { TEXT_COLORS, PRIMARY_COLORS } from '../../theme/colors';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  gradientContainer: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 20,
    width: '100%',
    minHeight: 300,
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingTop: 12,
    paddingBottom: 20,
  },
  leftSection: {
    flex: 1,
    marginRight: 16,
  },
  name: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
    color: '#FFFFFF',
    letterSpacing: 0,
  },
  address: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.8)',
    width: '100%',
    letterSpacing: 0,
  },
  toggleButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    minWidth: 70,
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  toggleButtonActive: {
    backgroundColor: PRIMARY_COLORS[500],
    borderColor: PRIMARY_COLORS[500],
  },
  toggleButtonInactive: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  toggleText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  toggleTextInactive: {
    color: 'rgba(255, 255, 255, 0.7)',
  },
  balanceSection: {
    paddingVertical: 16,
    paddingHorizontal: 0,
    gap: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  balanceInfo: {
    alignItems: 'center',
    gap: 4,
  },
  balanceLabel: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    color: '#FDD8AB',
    letterSpacing: 0,
  },
  balanceAmount: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '700',
    fontSize: 48,
    lineHeight: 56,
    color: '#FFFFFF',
    letterSpacing: -0.96,
  },
  earnMoreButton: {
    backgroundColor: '#FFFFFF1F',
    borderRadius: 1000,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  earnMoreText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
    letterSpacing: 0,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 0,
    gap: 12,
    paddingTop: 12,
    paddingBottom: 8,
  },
  actionButton: {
    backgroundColor: '#FFFFFF1F',
    borderRadius: 1000,
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: 52,
    height: 52,
  },
  actionButtonText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 16,
    color: '#FFFFFF',
    marginTop: 4,
    textAlign: 'center',
  },
  actionButtonContainer: {
    alignItems: 'center',
    flex: 1,
  },
  sectionContainer: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
  },
  sectionHeader: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 28,
    color: '#111827',
    letterSpacing: 0,
  },
  sectionall: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    color: '#6B7280',
    letterSpacing: 0,
  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 8,
    marginBottom: 8,
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: '#D5D7DA',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 36,
  },
  activeTabButton: {
    backgroundColor: PRIMARY_COLORS[900],
    borderColor: PRIMARY_COLORS[900],
  },
  inactiveTabButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D5D7DA',
  },
  tabButtonText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '500',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0,
  },
  activeTabButtonText: {
    color: '#FFFFFF',
  },
  inactiveTabButtonText: {
    color: '#252B37',
  },
  tabContent: {
    gap: 12,
    marginBottom: 16,
  },
  upcomingContent: {
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderRadius: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  contentText: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: '#111827',
  },
  contentSubtext: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 18,
    color: '#6B7280',
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  payBadge: {
    backgroundColor: '#FEEDD6',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  daysBadge: {
    backgroundColor: '#FEEDD6',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  completedBadge: {
    backgroundColor: '#E8F5E8',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  rejectedBadge: {
    backgroundColor: '#FFE5E5',
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 8,
  },
  performanceSection: {
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    marginTop: 8,
  },
  performanceCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  performanceCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  performanceIcon: {
    width: 40,
    height: 40,
  },
  performanceValue: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '600',
    fontSize: 16,
    color: '#111827',
  },
  performanceLabel: {
    fontFamily: 'Saans TRIAL',
    fontWeight: '400',
    fontSize: 12,
    color: '#6B7280',
  },
  footerSection: {
    gap: 8,
    paddingVertical: 32,
    backgroundColor: '#FFFFFF',
  },
  footerTitle: {
    color: '#FBBB76',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Saans TRIAL',
    lineHeight: 28,
  },
  footerSubtitle: {
    color: '#B7410E',
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'Saans TRIAL',
    lineHeight: 36,
  },
  footerDescription: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Saans TRIAL',
    lineHeight: 20,
  },
});
