import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  container: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
  },
  content: {
    padding: 0,
  },
  scrollContent: {
    paddingTop: 12,
    gap: 20,
  },
  handleLine: {
    width: "40%",
    height: 5,
    backgroundColor: '#D5D7DA',
    borderRadius: 2,
    alignSelf: 'center',
  },
  header: {
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  balanceCard: {
    backgroundColor: '#F5F3F0',
    borderRadius: 12,
    padding: 16,
    gap: 8,
  },
  balanceLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#252B37',
    fontFamily: 'Saans TRIAL',
  },
  balanceAmount: {
    fontSize: 32,
    fontWeight: '700',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  inputSection: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  amountInput: {
    height: 56,
    borderWidth: 1,
    borderColor: '#D5D7DA',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    fontSize: 16,
    fontWeight: '500',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  noteText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#717680',
    fontFamily: 'Saans TRIAL',
  },
  optionSection: {
    gap: 12,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  radioGroup: {
    gap: 12,
    flexDirection:'row',
    alignItems:'center'
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  radioButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#D5D7DA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonSelected: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#B7410E',
  },
  upiIcon: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 4,
  },
  upiIconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 24,
    height: 24,
    gap: 2,
  },
  upiIconSquare: {
    width: 10,
    height: 10,
    borderRadius: 2,
  },
  bankIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bankIconText: {
    fontSize: 20,
  },
  radioLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  dropdownSection: {
    gap: 8,
  },
  dropdown: {
    height: 56,
    borderWidth: 1,
    borderColor: '#D5D7DA',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  dropdownPlaceholder: {
    color: '#A4A7AE',
    fontWeight: '400',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#717680',
  },
  dropdownList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D5D7DA',
    overflow: 'hidden',
    marginTop: 4,
  },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  dropdownItemText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
  },
  infoBanner: {
    backgroundColor: '#FEF0C7',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal:12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  infoIcon: {
    fontSize: 20,
  },
  infoText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#B7410E',
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  termsSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#D5D7DA',
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    width: '100%',
    height: '100%',
    backgroundColor: '#B7410E',
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkmark: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  termsText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#181D27',
    fontFamily: 'Saans TRIAL',
    flex: 1,
  },
  termsLink: {
    color: '#B7410E',
    fontWeight: '600',
  },
  withdrawButtonTouchable: {
    borderRadius: 100,
    overflow: 'hidden',
    marginTop: 8,
  },
  withdrawButton: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  withdrawButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'Saans TRIAL',
  },
  withdrawButtonArrow: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});

